### ISSUE TITLE
Update Menus debug (type changed in Hugo 0.55)

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/hugo-debugprint#2]

**Comment by davidsneighbour** [comment]
I am able to debug menu entries by using the following "hacks":

Debugging:

```
{{ range .Site.Menus.main }}
  {{ partial "debugprint.html" . }}
{{ end }}
```

Changes in debugprint.html:35:

```
{{ $typeIsMenuEntry            := (findRE "MenuEntry$" $type) }}
```

The menu itself can be found by:

```
{{ $typeIsMenu                 := (findRE "Menu$" $type) }}
```

I don't know though what to do with it (I don't understand everything in this template ;) The debugged menu items look fine to me. 

Hope that helps.

**Comment by kaushalmodi** [comment]
@davidsneighbour Thanks for trying to help out with this.. it ended up being a bit more involved. Now the Menu debug seems to work as before based on basic testing.

![image](https://user-images.githubusercontent.com/3578197/60894522-dc51f780-a230-11e9-8541-907ecf417d39.png)

**Comment by davidsneighbour** [comment]
Very cool. I could have used that a week ago, that's why I was so pushy ;) Looking good!

**Comment by kaushalmodi** [comment]
> I could have used that a week ago

I was hiking in Acadia National Park in Maine then :). Though, I should have looked into fixing this issue a while back.

**Comment by davidsneighbour** [comment]
Nope. Clearing your brain is more important. Wizardry requires a de-stressed brain.
